name: Blackduck SCA scan
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    #env:
          #DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
          #BLACKDUCK_URL: "${{ secrets.BLACKDUCK_URL }}"
          #BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
          #BLACKDUCK_URL: "${{ secrets.BLACKDUCKURL }}"
          #BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCKAPITOKEN }}
          #detect-version: "7.13.2"
          
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: BlackDuck Scan
      uses: blackducksoftware/github-action@v2
      with:
        args: --blackduck.url=${{ secrets.BLACKDUCKURL }} --blackduck.api.token=${{ secrets.BLACKDUCKAPITOKEN }}
        #--detect.project.name=Pipeline_test --detect.tools.excluded="DETECTOR" --blackduck.trust.cert=true --detect.risk.report.pdf=true --detect.default.project.version.scheme=timestamp
        #--detect.project.version.name=3
        
    - run: ls 
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
        name: Blackduck
        path: /home/runner/work/insecure-bank/insecure-bank/
